name: 'Webifier Build'
description: 'GitHub Action to process repository contents for jekyll deployment on github pages'
author: 'webifier'
branding:
  color: 'blue'
  icon: 'cloud'

inputs:
  repo:
    description: 'GitHub repository of website material (default: $GITHUB_REPOSITORY)'
    default: ${{ github.repository }}
    required: false
  baseurl:
    description: >
      Base URL (slug) of website (default: name of repository). You should set this field to "" if you are using
      Webifier for building a github.io repository itself (in a `<username/organization>.github.io` repository ).
    default: ${{ github.event.repository.name }}
    required: false
  index:
    description: >
      Entry index file (default: index.yml) change this if your entry index file is not named "index.yml" or is not
      located in the root of your repository.
    default: 'index.yml'
    required: false
  templates_dir:
    description: >
      Base directory to lookup custom jinja2 templates in (default: ".").
    default: "."
    required: false
  publish_dir:
    description: >
      Where should the webified results end up (default: "./webified/")
    default: "./webified/"
    required: false
runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - run: pip install webifier
      shell: bash
    - run: webify --repo_full_name "${{ inputs.repo }}" --baseurl "${{ inputs.baseurl }}" --index ${{ inputs.index }} --output="${{ inputs.publish_dir }}" --templates-dir="${{ inputs.templates_dir }}"
      shell: bash


