title: SUT-AI
copyright_text: '2021 Copyright: <a class="text-white" href="https://github.com/SUT-AI">SUT AI</a> - Created by: <a class="text-white" href="https://github.com/ahmadsalimi">Ahmad Salimi</a>'
